// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-U_D60pEKc06wE0LbpyynTBmBW8Jz2U0',
    appId: '1:176884460820:web:caf7f79a61d5b6c063a601',
    messagingSenderId: '176884460820',
    projectId: 'fypstoreapp',
    authDomain: 'fypstoreapp.firebaseapp.com',
    storageBucket: 'fypstoreapp.appspot.com',
    measurementId: 'G-SRJ7DD7GTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_rEDbI_KiwCt1TlfMQuS_irG9tKhB4CU',
    appId: '1:176884460820:android:6b290929f6779b3b63a601',
    messagingSenderId: '176884460820',
    projectId: 'fypstoreapp',
    storageBucket: 'fypstoreapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwZVkMTOqf4DXaPeLfkxWqZ5e3DY5zqIM',
    appId: '1:176884460820:ios:88cf5d439679aac863a601',
    messagingSenderId: '176884460820',
    projectId: 'fypstoreapp',
    storageBucket: 'fypstoreapp.appspot.com',
    androidClientId: '176884460820-maf5i98f9lcd1h8utc5rti4v97dlkl29.apps.googleusercontent.com',
    iosClientId: '176884460820-fg2p1i3h5dtb3ic8q3d94liaiseves87.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypStore',
  );

}